import VerifiedCompiler.Compile

open Directive Operand Register

-- prints compiled code as x86-64 assembly for nasm. this part isn't verified: the proofs are
-- about the processor in `Process.lean`, and this is a direct translation of it.
--
-- - jumps skip a number of directives, so every jump target gets a label
-- - `Sub` stops at 0 in the model, so after a real `sub` a `cmovb` sets the result to 0 if
--   it went below
-- - the heap pointer starts wherever the runtime's heap is (in the model it starts at 0). no
--   instruction looks at a pointer except to follow it or check its tag, and the runtime's heap
--   is 16-byte aligned, so the tags still work
-- - words are 64 bits, so numbers have to stay below 2^62

def Register.asm : Register → String
| Rax => "rax"
| Rcx => "rcx"
| R8 => "r8"
| R15 => "r15"

-- x86 only takes 32-bit immediates (sign-extended) outside of `mov`, so larger ones go through
-- the scratch register r11, which the compiled code never uses
def bigImm (i : Nat) : Bool := i ≥ 2 ^ 31

-- `op dst, src` for an operand that might be a big immediate
def binop (op : String) (dst : String) : Operand → List String
| Reg r => [s!"{op} {dst}, {r.asm}"]
| Imm i => if bigImm i then [s!"mov r11, {i}", s!"{op} {dst}, r11"] else [s!"{op} {dst}, {i}"]

-- function names can have characters nasm doesn't allow in labels, like `?` or `-`
def mangle (f : String) : String :=
  "fn_" ++ String.join (f.toList.map fun c =>
    if c.isAlphanum then c.toString else s!"_{c.toNat}_")

def label (block : String) (i : Nat) : String :=
  s!".L{block}_{i}"

-- the instructions for one directive. `i` is its position in the block, for jump targets
def emitDirective (block : String) (i : Nat) : Directive → List String
| Mov (Reg r, Imm v) => [s!"mov {r.asm}, {v}"]
| Mov (Reg r, Reg s) => [s!"mov {r.asm}, {s.asm}"]
| Directive.Add (Reg r, o) => binop "add" r.asm o
| Directive.Sub (Reg r, o) => binop "sub" r.asm o ++ ["mov r11, 0", s!"cmovb {r.asm}, r11"]
| Directive.And (Reg r, o) => binop "and" r.asm o
| Cmp (Reg r, o) => binop "cmp" r.asm o
| Push (Reg r) => [s!"push {r.asm}"]
| Push (Imm v) => [s!"mov r11, {v}", "push r11"]
| Pop r => [s!"pop {r.asm}"]
| Load k => [s!"mov rax, [rsp + {8 * k}]"]
| LoadMem dst base off => [s!"mov {dst.asm}, [{base.asm} + {off}]"]
| StoreMem base off src => [s!"mov [{base.asm} + {off}], {src.asm}"]
| Jmp n => [s!"jmp {label block (i + 1 + n)}"]
| Je n => [s!"je {label block (i + 1 + n)}"]
| Jne n => [s!"jne {label block (i + 1 + n)}"]
| Jb n => [s!"jb {label block (i + 1 + n)}"]
| Call f => [s!"call {mangle f}"]
| Ret => ["ret"]
| Drop n => [s!"add rsp, {8 * n}"]
-- the C runtime's `lisp_error` prints "error" and exits. C functions want the stack 16-byte
-- aligned, and this one never returns, so it's fine to just align it
| Error => ["and rsp, -16", "call lisp_error wrt ..plt"]
-- these do nothing in the model (they would be a `mov` or `add` into a constant)
| Mov (Imm _, _) | Directive.Add (Imm _, _) | Directive.Sub (Imm _, _)
| Directive.And (Imm _, _) | Cmp (Imm _, _) => []

-- every directive that some jump in the block lands on
def jumpTargets (ds : List Directive) : List Nat :=
  (ds.zipIdx.filterMap fun (d, i) =>
    match d with
    | Jmp n | Je n | Jne n | Jb n => some (i + 1 + n)
    | _ => none)

def emitBlock (block : String) (ds : List Directive) : List String :=
  let targets := jumpTargets ds
  let lines := ds.zipIdx.flatMap fun (d, i) =>
    (if targets.contains i then [label block i ++ ":"] else []) ++
      (emitDirective block i d).map ("    " ++ ·)
  lines ++ (if targets.contains ds.length then [label block ds.length ++ ":"] else [])

def Directive.imm? : Directive → Option Nat
| Mov (_, Imm v) | Push (Imm v) | Directive.Add (_, Imm v) | Directive.Sub (_, Imm v)
| Directive.And (_, Imm v) | Cmp (_, Imm v) => some v
| _ => none

-- numbers are stored shifted left by 2, so anything from 2^62 up doesn't fit in a register
def fitsInWords (ds : List Directive) : Bool :=
  ds.all fun d => match d.imm? with
    | some v => v < 2 ^ 64
    | none => true

def emit (c : Compiled) : Except String String :=
  if !(fitsInWords c.main && c.funs.all (fitsInWords ·.2)) then
    .error "a number is too big for a 64-bit register"
  else
    let header := [
      "; generated by verified-compiler",
      "default rel",
      "global lisp_entry",
      "extern lisp_error",
      "section .note.GNU-stack noalloc noexec nowrite progbits",
      "section .text",
      "",
      -- the runtime passes the heap in rdi. r15 belongs to the caller, so save it first
      "lisp_entry:",
      "    push r15",
      "    mov r15, rdi"]
    let main := emitBlock "main" c.main ++ ["    pop r15", "    ret"]
    let funs := c.funs.zipIdx.flatMap fun ((f, body), j) =>
      ["", s!"{mangle f}:"] ++ emitBlock s!"f{j}" body
    .ok ("\n".intercalate (header ++ main ++ funs) ++ "\n")
